Todo App
melashu/Todo-App pull request #2
Opened 2022-09-22 20:44 UTC by melashu

# In this milestone I have done the following changes 

- Add routing 
- Add form validation 
- Implement the calculator functionality

2022-09-24 00:06 UTC, altontonn requested changes
# ♻️ CHANGES REQUIRED
Hi Melashu ☺️, Good job 👏 👏  on your project. 

<img src="https://media2.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>
You are almost there but there are changes that I consider you to make before merging your project.
Please work on your changes before submit

Happy coding ☺️

2022-09-24 00:06 UTC, altontonn commented on src/compontes/Header.jsx
> +    </header>
Kindly align the `header` tag on the same line as this will make you code more easier to read

2022-09-24 00:06 UTC, altontonn commented on src/compontes/SideBar.jsx
> +      </Routes> */}
Please delete this to make your code clean

2022-09-24 00:06 UTC, altontonn commented on src/compontes/demo.jsx
> +        </div>
Kindly remove the spaces below your `Link` element to to minimize the code space.

2022-09-24 00:06 UTC, altontonn commented on src/index.js
> -// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Please delete unnecessary code to make your code clean.

2022-09-24 00:06 UTC, altontonn commented on src/index.js
> +import App from './compontes/App';
Kindly do not add new line here, it is recommended to a new line after all of your `import` as this will make your code neat and easy to follow

2022-09-24 05:30 UTC, melashu commented on src/compontes/Header.jsx
> +    </header>
Thank you so much  @altontonn

2022-09-24 09:40 UTC, altontonn approved these changes

2022-09-24 19:58 UTC, merged

2023-02-27 10:27 UTC, altontonn reviewed
great